// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var WordUtils = require("word-utils/src/WordUtils.bs.js");

console.log("Hello, BuckleScript" + WordUtils.foo(/* () */0));

/*  Not a pure module */
